// client/src/views/Home.vue
<template>
  <div class="home">
    <h1>Home</h1>
    <GameArea />
    <div class="nav">
      <router-link to="/scoreboard">
        <button>ScoreBoard</button>
      </router-link>
      <router-link to="/help">
        <button>Help</button>
      </router-link>
    </div>
  </div>
</template>

<script>
import GameArea from "../components/GameArea";

export default {
  name: "Home",
  components: {
    GameArea
  }
};
</script>

<style scoped>
.home {
  text-align: center;
}
</style>

// client/src/pages/Home.jsx
import React from "react";
import { Link } from "react-router-dom";

function App() {
  return (
    <div>
      <h1>Home</h1>

      <nav>
        <Link to="/play">Play</Link>
        <Link to="/scoreboard">ScoreBoard</Link>
        <Link to="/help">Help</Link>
      </nav>
    </div>
  );
}

export default App;
